[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython",
    "oldest-supported-numpy",
    "gmpy2" # @ git+https://github.com/aleaxit/gmpy.git"
]
build-backend = "setuptools.build_meta"
