# -*- coding: utf-8 -*-
import os
from PyQt5 import QtCore
from PyQt5.QtWidgets import (QMainWindow, QApplication)

import fractalshades.gui as fsgui


def test_Image_widget():
    from viewer import Image_widget
    class Mywindow(QMainWindow):
    # https://doc.qt.io/qt-5/qmainwindow.html
        def __init__(self, im):
            """
            im is a path to an image (generated by py-fractal)
            """
            super().__init__(parent=None)
            self._im = im
            self.setWindowTitle('Testing Image of Fractalshades')
            self.xy_ratio = 1.0
            #self.setWindowState(Qt.WindowMaximized)
    
            # And don't forget to call setCentralWidget to your main layout widget.
            mw =  Image_widget(self) # fsgui.
            self.setCentralWidget(mw)

    im = os.path.join("/home/geoffroy/Pictures/math/github_fractal_rep/Fractal-shades/examples/flake",
                      "dev.png")

    app = QtCore.QCoreApplication.instance()
    if app is None:
        print("None")
        app = QApplication([])

    win = Mywindow(im)
    win.show()
    app.exec()


if __name__ == "__main__":
    test_Image_widget()
