# This is a basic workflow to help you get started with Actions

name: doc-latest

# Controls when the workflow will run
on:
  # Triggers the workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8] # , 3.9]

    env:
      DISPLAY: ':0'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Prepare GUI
        run: |
         echo "Prepare GUI for pyQt6"
          sudo apt-get update
          pip install --upgrade pip
          pip install pyQt6

          # See
          # https://github.com/pytest-dev/pytest-qt/issues/396
          # https://github.com/pytest-dev/pytest-qt/pull/295/files
          # https://github.com/konserw/mre/blob/master/.github/workflows/linux.yml
          # sudo apt install -y xvfb x11-utils libxkbcommon-x11-0
          # sudo apt-get -qq install libxcb-xinerama0 # xvfb x11-utils libxkbcommon-x11-0
          # sudo apt-get install libgl1
          # https://wiki.qt.io/Building_Qt_5_from_Git
          # sudo apt-get install libx11-xcb-dev libxcb-composite0-dev libxcb-cursor-dev libxcb-damage0-dev libxcb-dpms0-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-present-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-shm0-dev libxcb-sync-dev libxcb-util-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxcb-xtest0-dev libxcb1-dev
          # sudo apt-get install libxcb-xinerama0-dev 
          # https://moderngl.readthedocs.io/en/5.6.3/techniques/headless_ubuntu_18_server.html
          sudo apt-get install xvfb mesa-utils libegl1-mesa
          sudo apt-get install libxkbcommon-x11-0
          sudo apt-get install --reinstall libxcb-xinerama0
          dir /usr/lib/x86_64-linux-gnu
          echo "***********************"
          python3 -m site
          # dir /usr/lib/python3.8/site-packages/
          echo "***********************"
          dir /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages
          echo "***********************"
          dir /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/PyQt6/Qt/plugins/platforms
          echo "***********************##"
          ldd /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/PyQt6/Qt/plugins/platforms/libqxcb.so
          
          export DISPLAY=:99.0
          export QT_DEBUG_PLUGINS=1
          # export QT_PLUGIN_PATH=/usr/lib/qt/plugins
          # dir /usr/lib/qt/plugins
          # Xvfb :99 -screen 0 640x480x24 &
          
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
          

    
          # /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX


      - name: Install GMP MPFR MPC needed for gmpy2
        run: |
          sudo apt-get install libgmp-dev
          sudo apt-get install libmpfr-dev
          sudo apt-get install libmpc-dev



      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install flake8 pytest
          # pip install pyqt6-tools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: install Fractalshades from current commit
        run: |
          python -m pip install git+https://github.com/${{ github.repository }}.git@${{ github.sha }}

      - name: install dependencies to build the documentation
        run: |
          python -m pip install sphinx sphinx_rtd_theme sphinx-gallery numpydoc # matplotlib

      - name: Build documentation
        run: |
          python3 docs/doc_util.py
          make -C docs clean
          make -C docs html
  
      - name: Push documentation to github pages
        run: |
          git config --global user.email "geoffroy.billotey@gmail.com"
          git config --global user.name "GBillotey"
          docroot=`mktemp -d`
          rsync -av "docs/_build/html/" "${docroot}/"
          pushd "${docroot}"
          # don't bother maintaining history; just generate fresh
          git init
          git remote add deploy "https://token:${{ github.token }}@github.com/${{ github.repository }}.git"
          git checkout -b doc-latest
          git add .
          git commit -am "automatic triggered doc build"
          git push deploy doc-latest --force
          popd
